global using System.Text;
global using DotNet.CodeAnalysis;
global using DotNet.GitHubAction.Analyzers;
global using DotNet.GitHubAction.Extensions;
global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.CodeMetrics;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;