# This is a basic workflow to help you get started with Actions

name: 'Blueprint String to JSON'

# Controls when the workflow will run
on:
  # Triggers the workflow on push to main
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow'
        required: true
        default: 'Manual run'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build" (can name this whatever)
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code in repository
        uses: actions/checkout@v3

      # Log successful checkout
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      
      # Print the reason for the manual run if it applys
      - name: 'Print Manual Run Reason'
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        echo 'Reason: ${{ github.event.inputs.reason }}'

      - name: Blueprint String to JSON
        id: dotnet-code-metrics
        uses: dotnet/samples/github-actions/DotNet.GitHubAction@main
        env:
          GREETINGS: 'Hello, .NET developers!' # ${{ secrets.GITHUB_TOKEN }}
        with:
          #owner: ${{ github.repository_owner }}
          #name: ${{ github.repository }}
          #branch: ${{ github.ref }}
          dir: ${{ './github-actions/DotNet.GitHubAction' }}
      
      - name: Commit Changes
        if: ${{ steps.dotnet-code-metrics.outputs.was-blueprint-changed }} == 'true'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Blueprint String To JSON: automated pull request."
          git push
      
        #uses: peter-evans/create-pull-request@v4
        #if: ${{ steps.dotnet-code-metrics.outputs.was-blueprint-changed }} == 'true'
        #with:
          #title: '${{ steps.dotnet-code-metrics.outputs.summary-title }}'
          #body: '${{ steps.dotnet-code-metrics.outputs.summary-details }}'
          #commit-message: 'Blueprint String To JSON: automated pull request.'